/***************************************************************************** 
 * Project: RooFit                                                           * 
 *                                                                           * 
 * This code was autogenerated by RooClassFactory                            * 
 *****************************************************************************/ 

// Your description goes here... 

#include "Riostream.h" 

#include "RelativisticBreitWigner.h" 
#include "RooAbsReal.h" 
#include "RooAbsCategory.h" 
#include <math.h> 
#include "TMath.h" 

ClassImp(RelativisticBreitWigner); 

 RelativisticBreitWigner::RelativisticBreitWigner(const char *name, const char *title, 
                        RooAbsReal& _x,
                        RooAbsReal& _ A,
                        RooAbsReal& _ M,
                        RooAbsReal& _ W) :
   RooAbsPdf(name,title), 
   x("x","x",this,_x),
    A(" A"," A",this,_ A),
    M(" M"," M",this,_ M),
    W(" W"," W",this,_ W)
 { 
 } 


 RelativisticBreitWigner::RelativisticBreitWigner(const RelativisticBreitWigner& other, const char* name) :  
   RooAbsPdf(other,name), 
   x("x",this,other.x),
    A(" A",this,other. A),
    M(" M",this,other. M),
    W(" W",this,other. W)
 { 
 } 



 Double_t RelativisticBreitWigner::evaluate() const 
 { 
   // ENTER EXPRESSION IN TERMS OF VARIABLE ARGUMENTS HERE 
  double kaon = 0.49367;
  double proton = 0.93827;
  double pion = 0.13957;
  double k_short = 0.49761;

  double intermediateParticle = kaon + pion;

  Double_t q0 = breakupMomentum(M*M, intermediateParticle, k_short);
  Double_t q = breakupMomentum(x*x, intermediateParticle, k_short);

  spin = 0;

  double gamma = W * M / x * q/q0 * (barrierFactor(spin, q) / barrierFactor(spin, q0)) * (barrierFactor(spin, q) / barrierFactor(spin, q0));
  
  double arg1 = 14.0/22.0;
  double arg2 = M * M * gamma * gamma;
  double arg3 = (x*x - M*M) * (x*x - M*M);
  double arg4 = x*x*x*x*((gamma*gamma)/(M*M));
  return A * arg1 * arg2 / (arg3 + arg4); 
 } 


Double_t RelativisticBreitWigner::breakupMomentum(double s, double m1, double m2) const
{
  if(s < (m1+m2)*(m1+m2)){
    return 0.0;
  }
  else{
    double result = 0.5 * sqrt((s - (m1-m2)*(m1-m2)) * (s - (m1+m2)*(m1+m2)) / s);
    return result;
  }
}

Int_t RelativisticBreitWigner::barrierFactor(int L, double p){
  double hbarc = hbarc = 0.1973269631; //GeV*fm
  double z = (p/hbarc)*(p/hbarc);
  double barrier;

  switch(L){
    case 0:
      barrier = 1;
      break;
    case 1:
      barrier = sqrt(2 * z / (z + 1)); 
      break;
    case 2:
      barrier = sqrt(13 * z * z/ ((z-3)*(z-3) + 9*z));
      break;
    default:
      barrier = 0;
  }

  return barrier;
}
