/*****************************************************************************
 * Project: RooFit                                                           *
 *                                                                           *
  * This code was autogenerated by RooClassFactory                            * 
 *****************************************************************************/

#ifndef RELBREITWIGNER
#define RELBREITWIGNER

#include "RooAbsPdf.h"
#include "RooRealProxy.h"
#include "RooCategoryProxy.h"
#include "RooAbsReal.h"
#include "RooAbsCategory.h"
 
class RelBreitWigner : public RooAbsPdf {
public:
  RelBreitWigner() {} ; 
  RelBreitWigner(const char *name, const char *title,
	      RooAbsReal& _x,
	      RooAbsReal& _mean,
	      RooAbsReal& _width);
  RelBreitWigner(const RelBreitWigner& other, const char* name=0) ;
  virtual TObject* clone(const char* newname) const { return new RelBreitWigner(*this,newname); }
  inline virtual ~RelBreitWigner() { }

protected:

  RooRealProxy x ;
  RooRealProxy mean ;
  RooRealProxy width ;
  
  Double_t evaluate() const ;
    Double_t breakupMomentum(double s, double m1, double m2) const ;
  Int_t barrierFactor(int L, double p) const ;

private:

  ClassDef(RelBreitWigner,1) // Your description goes here...
};
 
#endif
