/*****************************************************************************
 * Project: RooFit                                                           *
 *                                                                           *
  * This code was autogenerated by RooClassFactory                            * 
 *****************************************************************************/

#ifndef RELBW
#define RELBW

#include "RooAbsPdf.h"
#include "RooRealProxy.h"
#include "RooCategoryProxy.h"
#include "RooAbsReal.h"
#include "RooAbsCategory.h"
 
class RelBW : public RooAbsPdf {
public:
  RelBW() {} ; 
  RelBW(const char *name, const char *title,
	      RooAbsReal& _x,
	      RooAbsReal& _A,
	      RooAbsReal& _M,
	      RooAbsReal& _W);
  RelBW(const RelBW& other, const char* name=0) ;
  virtual TObject* clone(const char* newname) const { return new RelBW(*this,newname); }
  inline virtual ~RelBW() { }

protected:

  RooRealProxy x ;
  RooRealProxy A ;
  RooRealProxy M ;
  RooRealProxy W ;
  
  Double_t evaluate() const ;
  Double_t breakupMomentum(double s, double m1, double m2) const ;
  Int_t barrierFactor(int L, double p) const ;

private:

  ClassDef(RelBW,1) // Your description goes here...
};
 
#endif
